name: Release

on:
  push:
    tags:
      - "*"

jobs:
  api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          yarn --frozen-lockfile
          yarn global add turbo@1.5.5

      - name: Docker login
        run: docker login -u bitmetro -p ${{ secrets.DOCKER_PASSWORD }} docker.io

      - name: Build and push api
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: bitmetro/identity-api:${{ github.ref_name }}
          build-args: |
            SCOPE=api
            PORT=5001

  client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          yarn --frozen-lockfile
          yarn global add turbo@1.5.5

      - name: Docker login
        run: docker login -u bitmetro -p ${{ secrets.DOCKER_PASSWORD }} docker.io

      - name: Build and push client
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: bitmetro/identity-client:${{ github.ref_name }}
          build-args: |
            SCOPE=client
            PORT=5002

  dashboard:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          yarn --frozen-lockfile
          yarn global add turbo@1.5.5

      - name: Docker login
        run: docker login -u bitmetro -p ${{ secrets.DOCKER_PASSWORD }} docker.io

      - name: Build and push dashboard
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: bitmetro/identity-dashboard:${{ github.ref_name }}
          build-args: |
            SCOPE=dashboard
            PORT=5003
